### ISSUE TITLE
 anchore-cli system wait takes a lot longer then before to complete

### ISSUE THREAD

**Issue by blacklabnz** [anchore/enterprise-docs#219]
Hi there

I have a task in azure devops to run the container image scanning using the following command that I followed in the quick start guide: (please ignore the variables that I used in the pipeline)

curl https://docs.anchore.com/current/docs/engine/quickstart/docker-compose.yaml > docker-compose.yaml
docker-compose up -d
docker-compose exec -T api anchore-cli system wait
docker-compose exec -T api anchore-cli registry list
docker-compose exec -T api anchore-cli registry add maed1intgrshrcr.azurecr.io maed1intgrshrcr $(acr-password-d1)
docker-compose exec -T api anchore-cli image add ${{ variables.acr_d1 }}.azurecr.io/integration/gam:$(Build.SourceVersion)
docker-compose exec -T api anchore-cli image wait ${{ variables.acr_d1 }}.azurecr.io/integration/gam:$(Build.SourceVersion)
docker-compose exec -T api anchore-cli image vuln ${{ variables.acr_d1 }}.azurecr.io/integration/gam:$(Build.SourceVersion) all
docker-compose exec -T api anchore-cli evaluate check ${{ variables.acr_d1 }}.azurecr.io/integration/gam:$(Build.SourceVersion)

it used to take about 5 min to complete the who scanning process and we were very impressed with the product.
However since today the anchore-cli system wait part takes longer time about an hour to complete which will leave us not choice but remove it from our CI pipeline as the waiting time is just to much.

could you please assist on this and see if there is anything I could do to resolve this. 

Thanks

**Comment by zhill** [comment]
Hi @blacklabnz, thanks for reaching out.

If you're looking for vulnerability results, an even better solution may be to checkout our new vulnerability scanning project: [Grype](https://github.com/anchore/grype). It may suit your needs even better since it's much faster and easier to install.

If you want to stick with Engine, the easiest thing you can do is try using our preload db image instead of the regular postgres image. That will use a pre-built db (built daily) instead of doing a feed sync to download the vulnerabilities each time. The initial sync time has grown as we've added more distro support, more distros have released more versions, and we have more vulnerability sources.

You can replace the db image reference in the docker-compose.yaml file:
```  
db:
    image: "postgres:9"
```
with 
```
db:
  image: "anchore/engine-db-preload:v0.8.1"
```

**Comment by zhill** [comment]
For use-cases of CI-pipeline scanning using the free/open-source code, we recommend using [Grype](https://github.com/anchore/grype) as that is our new and much faster way to do scans where you don't need to store the results and have them accessible via APIs.

**Comment by zhill** [comment]
I'm going to close this since there hasn't been an update, but feel free to re-open if there are other issues or follow-up is needed.
