### ISSUE TITLE
queue anchore images 

### ISSUE THREAD

**Issue by josiahrood1** [anchore/enterprise-docs#239]
i am trying to queue a base image that has already been scanned by anchore and do a vulnerability comparison with the other child images. since anchore has a previous scan of the base image i only want the vulnerability of the child image and nothing from the base image because the base image vulnerabilities have already been approved.

**Comment by zhill** [comment]
@josiahrood1 apologies for the delay, did you close because your question got answered? If not, there is a way in our Enterprise/Commercial product to get a vulnerability diff between an image and its base image (or a full policy eval diff), see https://docs.anchore.com/current/docs/overview/concepts/images/base_images/.

**Comment by josiahrood1** [comment]
@zhill yes sir, I found out that the enterprise/commercial license does this and looking into it. This process would be much more efficient then having to run both vulnerabilities and then reading both files in and looking for matches and removing them. my goal was to only receive the child image vulnerabilities because the base image should already be approved and other vulnerabilities justified. Thank you sir.
